Question: 1. What is a Python library? Why do we use Python libraries?

Answe: Python library is collection pre written code amd function which we can use in single click. We use python libraries for creating applications and models in a variety of fields, for instance, machine learning, data science, data visualization, image and data manipulation, and many more.

Question: 2. What is the difference between Numpy array and List?

Answer:

Numpy array: Numpy arrays are multidimensional arrays in Python that are used for a wide range of data analysis, visualization, and machine learning tasks. Numpy arrays can be of various data types such as integers, floating-point numbers, complex numbers, and Boolean values. They provide several methods for array operations, such as slicing, reshaping, indexing, and aggregation. Numpy arrays are optimized for performance and are commonly used in scientific computing and data science workflows.

NumPy arrays are much faster and have strict requirements on the homogeneity of the objects. For example, a NumPy array of strings can only contain strings and no other data types.

In [3]:
#Here is an example of creating a simple Numpy array:

import numpy as np

# create a 2D array of shape (3, 4) with values from 0 to 9
arr = (3,4)

List: Python list can contain a mixture of strings, numbers, booleans and other objects.

Question: 3. Find the shape, size and dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [5]:
#Answer


import numpy as np


my_array = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]])


shape_of_array = my_array.shape


size_of_array = my_array.size


dimension_of_array = my_array.ndim


print("Shape of the array:", shape_of_array)
print("Size of the array:", size_of_array)
print("Dimension of the array:", dimension_of_array)


Shape of the array: (3, 4)
Size of the array: 12
Dimension of the array: 2


Question: 4. Write python code to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [6]:
#Answer


import numpy as np


my_array = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]])


first_row = my_array[0, :]


In [7]:
print("First row of the array:", first_row)

First row of the array: [1 2 3 4]


Question: 5. How do you access the element at the third row and fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [9]:
#Answer

import numpy as np


In [10]:
my_array = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]])


element = my_array[2, 3]

In [11]:
print("Element at the third row and fourth column:", element)

Element at the third row and fourth column: 12


Question: 6. Write code to extract all odd-indexed elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [12]:
#Answer

import numpy as np

In [13]:
my_array = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12]])

odd_indexed_elements = my_array[:, 1::2]


In [14]:
print("Odd-indexed elements:", odd_indexed_elements.flatten())

Odd-indexed elements: [ 2  4  6  8 10 12]


Question: 7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [17]:
#Answer

import numpy as np


In [18]:
random_matrix = np.random.rand(3, 3)


In [19]:
print("Random 3x3 matrix with values between 0 and 1:\n", random_matrix)

Random 3x3 matrix with values between 0 and 1:
 [[0.53944344 0.50548786 0.09229335]
 [0.65411035 0.32743631 0.83654992]
 [0.3020603  0.48543343 0.25088795]]


Question: 8. Describe the difference between np.random.rand and np.random.randn?

In [22]:
#Answer

#np.random.rand

import numpy as np


In [21]:
random_numbers = np.random.rand(2, 3) 

In [26]:
# Generates a 2x3 array of random numbers between 0 and 1

In [23]:
#np.random.rand

import numpy as np 


In [24]:
random_numbers = np.random.randn(2, 3) 

In [25]:
# Generates a 2x3 array of random numbers from a standard normal distribution

Question: 9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [27]:
#Answer


import numpy as np

In [28]:
original_array = np.array([[1, 2, 3, 4],
                           [5, 6, 7, 8],
                           [9, 10, 11, 12]])


increased_dimension_array = original_array[:, :, np.newaxis]


In [29]:
print("Original Array:\n", original_array)
print("\nArray with Increased Dimension:\n", increased_dimension_array)

Original Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Array with Increased Dimension:
 [[[ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]
  [12]]]


Question: 10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]


Perform the following operation using Python1
1. Index wise multiplication
2. Matrix multiplication
3. Add both the matics
4. Subtract matrix B from A
5. Divide Matrix B by A

In [3]:
#Answer

import numpy as np


In [31]:
original_array = np.array([[1, 2, 3, 4],
                           [5, 6, 7, 8],
                           [9, 10, 11, 12]])


transposed_array_1 = original_array.T

transposed_array_2 = np.transpose(original_array)

In [32]:
print("Original Array:\n", original_array)
print("\nTransposed Array (using .T attribute):\n", transposed_array_1)
print("\nTransposed Array (using np.transpose() function):\n", transposed_array_2)

Original Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Transposed Array (using .T attribute):
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]

Transposed Array (using np.transpose() function):
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [2]:
import numpy as np

# Define matrices A and B
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
B = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# 1. Index wise multiplication
index_wise_multiplication = A * B
print("Index wise multiplication:")
print(index_wise_multiplication)

# 2. Matrix multiplication
matrix_multiplication = np.dot(A, B.T)  
print("\nMatrix multiplication:")
print(matrix_multiplication)

# 3. Add both the matrices
matrix_addition = A + B
print("\nMatrix addition:")
print(matrix_addition)

# 4. Subtract matrix B from A
matrix_subtraction = A - B
print("\nMatrix subtraction (A - B):")
print(matrix_subtraction)

# 5. Divide Matrix B by A
matrix_division = np.divide(B, A)
print("\nMatrix division (B / A):")
print(matrix_division)


Index wise multiplication:
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]

Matrix multiplication:
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]

Matrix addition:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

Matrix subtraction (A - B):
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Matrix division (B / A):
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Question 12. Which function in Numpy can be used to swap the byte order of an array?

Asnwer


In NumPy, the function np.ndarray.byteswap() can be used to swap the byte order of an array. 

In [12]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype=np.int16)

print("Original array:")
print(arr)

arr.byteswap(True)

print("\nArray after byte swapping:")
print(arr)


Original array:
[1 2 3 4]

Array after byte swapping:
[ 256  512  768 1024]


Question 13. What is the significance of the np.linalg.inv function?

Answer


The np.linalg.inv function in NumPy is used to compute the multiplicative inverse of a matrix. 

In [13]:
import numpy as np

A = np.array([[1, 2], [3, 4]])

A_inv = np.linalg.inv(A)

print("Original Matrix:")
print(A)
print("\nInverse of the Matrix:")
print(A_inv)


Original Matrix:
[[1 2]
 [3 4]]

Inverse of the Matrix:
[[-2.   1. ]
 [ 1.5 -0.5]]


Question 14. What does the np.reshape function do, and how is it used?

Answer

The np.reshape function in NumPy is used to change the shape (dimensions) of an array while maintaining the same elements.

In [10]:
import numpy as np


arr = np.array([1, 2, 3, 4, 5, 6])

reshaped_arr = np.reshape(arr, (2, 3))

print(reshaped_arr)


[[1 2 3]
 [4 5 6]]


Question 15. What is broadcasting in Numpy?

Answer

Broadcasting in NumPy is a powerful mechanism that allows us to perform operations on arrays of different shapes. This is done by automatically expanding the smaller array to match the dimensions of the larger array.

In [11]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

b = np.array([10, 11, 12])

result = a + b

print(result)


[[11 13 15]
 [14 16 18]
 [17 19 21]]
